Add Count methods
utopia-php/audit pull request #21
Opened 2021-11-16 14:32 UTC by TorstenDittmann

- add count methods
- added private helper method for DRY code
- replaced mysql with mariadb

2021-11-16 19:42 UTC, kodumbeats commented on docker-compose.yml
> +      - MARIADB_ROOT_PASSWORD=password
I don't think we need to change this, since MariaDB is a drop-in replacement for MySQL. We leave it be in Appwrite:

https://github.com/appwrite/appwrite/blob/a917746ac947fee17ff01a2781b753589f6d32b7/docker-compose.yml#L447

```suggestion
      - MYSQL_ROOT_PASSWORD=password
```

2021-11-16 19:45 UTC, kodumbeats commented on src/Audit/Audit.php
> +    public function getLogsByUserCount(string $userId): int
I don't like this method name - does `countLogsByUser()` sound better?

2021-11-16 19:46 UTC, kodumbeats commented on src/Audit/Audit.php
> +    public function getLogsByResourceCount(string $resource): int
Same thing here - does `countLogsByResource()` sound better?

2021-11-16 19:47 UTC, kodumbeats commented on src/Audit/Audit.php
> +    public function getLogsByUserAndEventsCount(string $userId, array $events): int
`countLogsByUserAndEvents`?

2021-11-16 22:50 UTC, TorstenDittmann commented on src/Audit/Audit.php
> +    public function getLogsByUserCount(string $userId): int
I agree, gonna update according to your suggestions :+1:

2021-11-17 16:19 UTC, kodumbeats requested changes

2021-11-17 16:19 UTC, kodumbeats commented on composer.json
> +        "utopia-php/database": "0.11.*"
```suggestion
        "utopia-php/database": ">=0.11 <1.0"
```

2021-11-17 17:23 UTC, merged