first draft using utopia-php database
utopia-php/audit pull request #9
Opened 2021-05-16 13:56 UTC by lohanidamodar

2021-05-16 14:57 UTC, eldadfux requested changes

2021-05-16 14:57 UTC, eldadfux commented on src/Audit/Audit.php
> +        $this->init();
We don't have to trigger init on the constructor.

2021-05-16 14:57 UTC, eldadfux commented on src/Audit/Audit.php
> +    private function init(): void
Double thinking about it, I think `install` or `setup` might better describe this method.

2021-05-16 14:57 UTC, eldadfux commented on src/Audit/Audit.php
> +            $this->db->createAttribute(Audit::COLLECTION, 'userId', Database::VAR_STRING, 45, true);
```suggestion
            $this->db->createAttribute(Audit::COLLECTION, 'userId', Database::VAR_STRING, Database::LENGTH_KEY, true);
```

2021-05-16 14:57 UTC, eldadfux commented on src/Audit/Audit.php
> +            $this->db->createAttribute(Audit::COLLECTION, 'data', Database::VAR_STRING, 16777216, false,true,false,['json']);
```suggestion
            $this->db->createAttribute(Audit::COLLECTION, 'event', Database::VAR_STRING, 255, true);
            $this->db->createAttribute(Audit::COLLECTION, 'resource', Database::VAR_STRING, 255, false);
            $this->db->createAttribute(Audit::COLLECTION, 'userAgent', Database::VAR_STRING, 65534, true);
            $this->db->createAttribute(Audit::COLLECTION, 'ip', Database::VAR_STRING, 45, true);
            $this->db->createAttribute(Audit::COLLECTION, 'location', Database::VAR_STRING, 45, false);
            $this->db->createAttribute(Audit::COLLECTION, 'time', Database::VAR_INTEGER, 0, true, false);
            $this->db->createAttribute(Audit::COLLECTION, 'data', Database::VAR_STRING, 16777216, false,true,false,['json']);
```

2021-05-16 14:57 UTC, eldadfux commented on src/Audit/Audit.php
> +        return true;
Reset authorization back, leaving it disable could lead to a security bridge.

2021-05-16 14:57 UTC, eldadfux commented on src/Audit/Audit.php
> +    const COLLECTION = "abuse";
```suggestion
    const COLLECTION = "audit";
```

2021-05-16 14:57 UTC, eldadfux commented on tests/Audit/AuditTest.php
> +
Extra space

2021-05-16 14:57 UTC, eldadfux commented on src/Audit/Audit.php
> +
We can also add a shared index for userId and event

2021-05-16 14:57 UTC, eldadfux commented on src/Audit/Audit.php
>      public function getLogsByUserAndActions(string $userId, array $actions): array
Let's fix the naming conventions. Action\s == Event\s

2021-05-16 21:49 UTC, eldadfux commented on src/Audit/Audit.php
>      /**
```suggestion

    /**
```

2021-05-16 21:51 UTC, eldadfux commented
We should also update the readme examples with the new changes

2021-05-17 08:37 UTC, eldadfux requested changes

2021-05-17 08:37 UTC, eldadfux commented on README.md
> +use PHPUnit\Framework\TestCase;
```suggestion
```

2021-05-17 08:37 UTC, eldadfux commented on README.md
> +$this->audit->setup();
```suggestion
$audit = new Audit($database);
$audit->setup();
```

2021-06-09 16:07 UTC, kodumbeats requested changes
the `getLogs` methods state in their description to "get all logs", but without passing a limit, only the default limit of 25 will be returned.

2021-06-09 16:07 UTC, kodumbeats commented on composer.json
> +        "utopia-php/database": "0.2.*"
Upgrade to `utopia-php/database` 0.3?

2021-06-10 05:47 UTC, lohanidamodar commented
> the `getLogs` methods state in their description to "get all logs", but without passing a limit, only the default limit of 25 will be returned.

It should be fine. I think we are using that only for tests.

2021-06-10 11:18 UTC, eldadfux approved these changes

2021-06-10 12:01 UTC, kodumbeats requested changes
Minor question

2021-06-10 12:01 UTC, kodumbeats commented on tests/Audit/AuditTest.php
> +    protected $initialized = false;
Is this variable used anywhere?

2021-06-12 16:26 UTC, eldadfux commented
Seems like we need to apply a default order for the logs in all `find()` methods using ['_id'] as the attribute and `DESC` as the order type. For some reason the `time` attribute also seems wrong.

![image](https://user-images.githubusercontent.com/1297371/121782805-08601b00-cbb4-11eb-9b5b-90c897a54088.png)

2021-06-12 16:38 UTC, eldadfux commented
I've found and fixed the date format problem on appwrite/appwrite, we just need to fix the logs ordering.

2021-06-13 15:43 UTC, eldadfux commented
@lohanidamodar one last thing, I think we should change `getLogsByUserAndActions` to `getLogsByUserAndEvents`

2021-06-14 07:38 UTC, lohanidamodar commented
> @lohanidamodar one last thing, I think we should change `getLogsByUserAndActions` to `getLogsByUserAndEvents`

Done!

2021-08-01 11:14 UTC, merged